- type: entity
  id: LockerMimeFilled
  suffix: Filled
  parent: LockerMime
  components:
  - type: StorageFill
    contents:
      - id: ClothingUniformJumpsuitMime
      - id: ClothingUniformJumpskirtMime
      - id: ClothingShoesColorWhite
      - id: CrayonMime
      - id: RubberStampMime
      - id: DrinkBottleOfNothingFull
      - id: ClothingMaskMime
